#!/usr/bin/env bash

function usage() {
  echo "Usage: msto NAME"
}

if [ "$#" -lt "1" ]; then
  usage
  echo "Too few arguments"
  exit 1
fi

if [ "$#" -gt "1" ]; then
  usage
  echo "Too many arguments"
  exit 1
fi

name="$1"
cat<&0 > /dev/shm/"$name"
